//! Embeds the definitions omh ships into the binary.
//!
//! `adapters/`, `editors/` and `base/` are data, and omh copies them into
//! `~/.omh` on `init`. They used to be *read* from the source tree at runtime
//! via `env!("CARGO_MANIFEST_DIR")`, which meant a binary only worked on the
//! machine that compiled it. This turns them into `include_str!`, so what
//! `init` copies from travels inside the executable.
//!
//! Emits `$OUT_DIR/bundled.rs`:
//!
//! ```ignore
//! pub static BUNDLED: &[(&str, &[(&str, &str)])] = &[
//!     ("adapters", &[("claude.toml", include_str!("/abs/.../claude.toml")), ..]),
//! ];
//! ```

use std::path::Path;

/// The directories omh ships. A directory that is missing or empty is a build
/// failure rather than an empty entry: shipping an omh with no adapters is the
/// silent failure this whole change exists to remove, and it should not be
/// possible to produce one.
const SHIPPED: [&str; 3] = ["adapters", "base", "editors"];

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets this");
    let out = std::env::var("OUT_DIR").expect("cargo sets this");

    let mut generated = String::from(
        "// Generated by build.rs. Edit the .toml files, not this.\n\
         pub static BUNDLED: &[(&str, &[(&str, &str)])] = &[\n",
    );

    for kind in SHIPPED {
        let dir = Path::new(&manifest).join(kind);

        // Re-run when a file is added or removed, not only when one is edited.
        println!("cargo:rerun-if-changed={}", dir.display());

        let listing = std::fs::read_dir(&dir)
            .unwrap_or_else(|e| panic!("omh ships {kind}/, and it is unreadable: {e}"));

        let mut files: Vec<_> = listing
            .flatten()
            .map(|e| e.path())
            .filter(|p| p.extension().is_some_and(|x| x == "toml"))
            .collect();
        files.sort();

        assert!(
            !files.is_empty(),
            "{kind}/ holds no .toml — that would build an omh that installs nothing"
        );

        generated.push_str(&format!("    ({kind:?}, &[\n"));
        for file in files {
            let name = file
                .file_name()
                .expect("a path from read_dir has a final component")
                .to_string_lossy()
                .into_owned();
            println!("cargo:rerun-if-changed={}", file.display());
            generated.push_str(&format!(
                "        ({:?}, include_str!({:?})),\n",
                name,
                file.display().to_string()
            ));
        }
        generated.push_str("    ]),\n");
    }

    generated.push_str("];\n");

    std::fs::write(Path::new(&out).join("bundled.rs"), generated)
        .expect("writing the generated table");
}
