//! The definitions omh ships — adapters, editors, the base set — embedded in
//! the binary at compile time.
//!
//! They used to be read from `env!("CARGO_MANIFEST_DIR")` at *runtime*, which
//! is the build machine's source path. On the machine that built it that path
//! exists and everything works; anywhere else `read_dir` fails, the error is
//! discarded, and `omh init` delivers nothing while reporting success. A
//! downloaded binary got `no usable base manifest — run omh init` from `omh
//! init` itself, and zero adapters with no message at all.
//!
//! A `cargo install` would have escaped it, but only by accident: cargo leaves
//! the extracted crate under `~/.cargo/registry/src/`, so the baked path would
//! have resolved for as long as that directory survived — and it is a cache.
//! Stated as reasoning rather than history: omh has never been published, so
//! nobody has actually been bitten this way. The measured case was a binary
//! separated from the tree it was built in.
//!
//! Embedding is what makes the binary the unit of distribution. Note that the
//! files still land on disk in `~/.omh` exactly as before — the base set stays
//! reviewable by the people it is imposed on, which was always the point of
//! shipping it as data. Only where `init` copies *from* has changed.

// Generated by build.rs: `BUNDLED: &[(&str, &[(&str, &str)])]`, one entry per
// directory, each holding (file name, file contents) sorted by name.
include!(concat!(env!("OUT_DIR"), "/bundled.rs"));

/// The files omh ships for `kind`, or `None` if it ships no such directory.
///
/// `None` rather than an empty slice: an unknown kind is a programming error,
/// and returning "nothing to install" would let it land as an empty `~/.omh`
/// that looks like a successful install.
pub fn files(kind: &str) -> Option<&'static [(&'static str, &'static str)]> {
    BUNDLED
        .iter()
        .find(|(name, _)| *name == kind)
        .map(|(_, files)| *files)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// What ships and what is in the repo are the same set.
    ///
    /// This is not the guard against the bug that prompted the change — no
    /// in-process test can be, because during `cargo test` the source tree is
    /// right there and the old code worked fine. That one is a CI job that
    /// runs the built binary with no checkout at all.
    ///
    /// What this catches is the next failure: a `.toml` added to the repo that
    /// `build.rs` does not pick up, which would ship an omh missing an adapter
    /// while every other test stayed green.
    #[test]
    fn everything_in_the_repo_is_embedded_byte_for_byte() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
        for kind in ["adapters", "base", "editors"] {
            let embedded = files(kind).expect("a shipped directory must be embedded");

            let mut on_disk: Vec<String> = std::fs::read_dir(root.join(kind))
                .unwrap()
                .flatten()
                .map(|e| e.path())
                .filter(|p| p.extension().is_some_and(|x| x == "toml"))
                .map(|p| p.file_name().unwrap().to_string_lossy().into_owned())
                .collect();
            on_disk.sort();

            let names: Vec<String> = embedded.iter().map(|(n, _)| n.to_string()).collect();
            assert_eq!(
                names, on_disk,
                "{kind}: the binary and the repo disagree about what omh ships"
            );

            for (name, contents) in embedded {
                let disk = std::fs::read_to_string(root.join(kind).join(name)).unwrap();
                assert_eq!(*contents, disk, "{kind}/{name} was embedded stale");
            }
        }
    }

    /// A directory that embedded as empty would install nothing and say so
    /// nowhere — the exact shape of the bug this module exists to remove.
    #[test]
    fn no_shipped_directory_is_empty() {
        for kind in ["adapters", "base", "editors"] {
            assert!(
                !files(kind).expect("embedded").is_empty(),
                "{kind} embedded as empty"
            );
        }
    }

    /// `omh <anything>` is a harness, so a missing adapter is not a small loss.
    #[test]
    fn the_adapters_omh_launches_are_among_them() {
        let names: Vec<&str> = files("adapters").unwrap().iter().map(|(n, _)| *n).collect();
        assert!(names.contains(&"claude.toml"), "got: {names:?}");
        assert!(names.contains(&"opencode.toml"), "got: {names:?}");
    }

    #[test]
    fn a_directory_omh_does_not_ship_is_none_rather_than_empty() {
        assert!(files("skills").is_none());
    }
}
